name: Update README

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    readme-update:
        name: Update README
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - uses: charmbracelet/readme-scribe@master
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
                  WAKATIME_API_KEY: ${{ secrets.HACKATIME_API_KEY }}
                  WAKATIME_URL: https://hackatime.hackclub.com/api/hackatime/v1
              with:
                  template: "README.md.tpl"
                  writeTo: "README.md"

            - uses: stefanzweifel/git-auto-commit-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              with:
                  commit_message: Update generated README
                  branch: main
                  commit_user_name: Emilien X
                  commit_user_email: contact@oriondev.fr
                  commit_author: oriionn <contact@oriondev.fr>
